### ISSUE TITLE
process hangs/ slaves not responding. Easy to reproduce

### ISSUE THREAD

**Issue by bwflood** [hcoles/triangle-example#1]
## Summary

New to pitest, trying to invoke  mutationCoverage via maven and it appears the slaves are not communicating. 

I am able to reproduce the issue with the triangle-example project. With the -verbose option off, mutations are generated and reports show what I would expect. However, when I add -Dverbose=true, the process hangs.

https://github.com/hcoles/triangle-example (commit: 8d6ddcc2149f8aa953b0c432ea33a1d2f0a1c6a6)
## Environment

Windows 7 Enterprise 64 bit
Apache Maven 2.2.1 (r801777; 2009-08-06 14:16:01-0500)
Java version: 1.6.0_22
Java home: C:\softwaredistribution\Sun\jdk1.6.0_22\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7" version: "6.1" arch: "x86" Family: "windows"

Note: the results described below are the same for both pitest 1.1.6 and pitest 1.1.7-SNAPSHOT 
## Test 1 -- mvn clean install org.pitest:pitest-maven:mutationCoverage

works as expected
output truncated, but contains the following mutator results
MathMutator killed 100%
ConditionalsBoundaryMutator killed 20%
ReturnValsMutator killed 100%
NegateConditionalsMutator killed 100%
## Test 2 - mvn clean install -Dverbose=true org.pitest:pitest-maven:mutationCoverage

[INFO] [jar:jar {execution: default-jar}]
[INFO] Building jar: C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\target\triangle-0.0.1-SNAPSHOT.jar
[INFO] [pitest:mutationCoverage {execution: verify}]
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Default limit mutations plugin
[INFO] Found shared classpath plugin : Default mutation engine
[INFO] Adding org.pitest:pitest to SUT classpath
[INFO] Mutating from C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\target\classes
[INFO] Defaulting to group id (com.example_)
1:03:58 PM PIT >> FINE : Running report with ReportOptions [targetClasses=[^com.example._$], excludedMethods=[], excludedClasses=[], codePaths=[C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\target\classes],reportDir=C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\target\pit-reports, historyInputLocation=null, historyOutputLocation=null, sourceDirs=[C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\src\main\java, C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\src\test\java], classPathElements=[C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\target\test-classes,C:\Users\Brad.Flood\Documents\mutation testing\pitest\triangle-example-master\target\classes, C:\softwaredistribution.m2\repository\junit\junit\4.11\junit-4.11.jar, C:\softwaredistribution.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar, C:\softwaredistribution.m2\repository\org\pitest\pitest\1.1.7-SNAPSHOT\pitest-1.1.7-SNAPSHOT.jar], mutators=[STRONGER], dependencyAnalysisMaxDistance=-1, mutateStaticInitializers=false, jvmArgs=[], numberOfThreads=1, timeoutFactor=1.25, timeoutConstant=3000, targetTests=[], loggingClasses=[], maxMutationsPerClass=-1, verbose=true, failWhenNoMutations=true, outputs=[HTML], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], mutationUnitSize=0, shouldCreateTimestampedReports=true, detectInlinedCode=true, exportLineCoverage=false, mutationThreshold=0, coverageThreshold=0, mutationEngine=gregor, javaExecutable=null, includeLaunchClasspath=true]
1:03:58 PM PIT >> FINE : System class path is C:\softwaredistribution\apache-maven-2.2.1\boot\classworlds-1.1.jar;C:\softwaredistribution\apache-maven-2.2.1\boot\ci-utils-1.0.jar
1:03:58 PM PIT >> FINE : Maximum available memory is 494 mb
1:03:58 PM PIT >> FINE : using port 8092
1:03:58 PM PIT >> INFO : Sending 1 test classes to slave
1:03:58 PM PIT >> INFO : Sent tests to slave
<never returns>

**Comment by hcoles** [comment]
The way you are invoking pitest is a little strange.

As pitest is bound in the pom to the verify stage you only need

```
mvn clean install -Dverbose=true
```

If pitest were not bound to a phase in the pom then you would invoke the goal directly as you were doing.

The really interesting bit is that if I directly invoke the goal (after earlier running the tests) with

```
mvn  -Dverbose=true org.pitest:pitest-maven:mutationCoverage
```

Then everything runs fine

However if I do

```
mvn -Dverbose=true verify
```

Then I can reproduce the problem with 1.1.6 and 1.1.7-SNAPSHOT.

1.1.5 seems to be unaffected.

Thanks for the report.

**Comment by hcoles** [comment]
@bwflood Thanks again for reporting this.

It's now being tracked under an issue at the main pitest repo here

https://github.com/hcoles/pitest/issues/231

A fix is being tested at the moment.
